package com.company.internmgmt.dto;

import java.time.LocalDate;

import com.company.internmgmt.enums.IdCardType;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class InternRequestDto {

    // No internId field: it's generated by the backend at creation time and
    // never editable afterwards. The batch assignment is also immutable here —
    // re-batching an intern would silently rewrite their history.
    @NotBlank(message = "name is required")
    @Size(max = 100, message = "name must be at most 100 characters")
    private String name;

    // @Size mirrors the DB column length so oversized input is rejected with a
    // clean 400 instead of surfacing as a database error (500).
    @NotBlank(message = "email is required")
    @Email(message = "email must be a valid address")
    @Size(max = 255, message = "email must be at most 255 characters")
    private String email;

    // Mobile is kept as a string (leading zeros/`+` are meaningful and it's
    // never used in arithmetic); the regex rejects anything that isn't an
    // optional country code followed by 10-15 digits.
    @NotBlank(message = "mobile is required")
    @Pattern(regexp = "^\\+?[0-9]{10,15}$", message = "mobile must be 10-15 digits, optional leading +")
    @Size(max = 20, message = "mobile must be at most 20 characters")
    private String mobile;

    @NotNull(message = "idCardType is required (FREE or PREMIUM)")
    private IdCardType idCardType;

    @NotNull(message = "dateOfJoining is required")
    private LocalDate dateOfJoining;

    @NotNull(message = "batchId is required")
    private Long batchId;
}
