package com.company.internmgmt.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;

import com.company.internmgmt.enums.IdCardType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "intern", uniqueConstraints = @UniqueConstraint(name = "uk_intern_intern_id", columnNames = "intern_id"))
@Getter
@Setter
@NoArgsConstructor
public class Intern {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Generated by IdGeneratorService at creation time; immutable afterwards.
    @Column(name = "intern_id", nullable = false, updatable = false, length = 20)
    private String internId;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String email;

    @Column(nullable = false)
    private String mobile;

    @Enumerated(EnumType.STRING)
    @Column(name = "id_card_type", nullable = false, length = 10)
    private IdCardType idCardType;

    @Column(name = "date_of_joining", nullable = false)
    private LocalDate dateOfJoining;

    // One batch holds many interns; every intern must belong to exactly one
    // (NOT NULL enforced here and at the DB level). LAZY keeps batch data from
    // being pulled in whenever an Intern is loaded — controllers read it via
    // the batch overview endpoint instead.
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "batch_id", nullable = false)
    private Batch batch;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = createdAt;
    }

    @PreUpdate
    void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
