-- IDMS initial schema (Phase B1). Kept idempotent so it is safe both on a
-- fresh database and on one that was previously created by Hibernate's
-- ddl-auto=update (baseline-on-migrate skips it there anyway).
--
-- Column types mirror what Hibernate 6 expects when validation is enabled:
--   LocalDateTime -> timestamp(6), LocalDate -> date, IDENTITY -> bigint identity.

CREATE TABLE IF NOT EXISTS batch (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date date        NOT NULL,
    end_date   date        NOT NULL,
    created_at timestamp(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS intern (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intern_id       varchar(20)  NOT NULL,
    name            varchar(255) NOT NULL,
    email           varchar(255) NOT NULL,
    mobile          varchar(255) NOT NULL,
    id_card_type    varchar(10)  NOT NULL,
    date_of_joining date         NOT NULL,
    batch_id        bigint       NOT NULL,
    created_at      timestamp(6) NOT NULL,
    updated_at      timestamp(6),
    CONSTRAINT uk_intern_intern_id UNIQUE (intern_id),
    CONSTRAINT fk_intern_batch FOREIGN KEY (batch_id) REFERENCES batch (id)
);
