import {
  ChangeDetectionStrategy,
  Component,
  OnInit,
  ViewEncapsulation,
  inject,
  signal
} from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { BatchService } from '@core/services/batch.service';
import { InternService } from '@core/services/intern.service';
import { apiErrorMessage } from '@core/utils/api-error.util';
import { IdCardType, Intern, MOBILE_PATTERN } from '@data/schema/intern/intern';
import { Loader } from '@shared/components/loader/loader';
import { Spinner } from '@shared/components/spinner/spinner';
import { ToastService } from '@shared/components/toast/toast.service';

const INPUT_CLASS =
  'w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 px-3 py-2 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-primary-200 dark:focus:ring-primary-700';

@Component({
  selector: 'intern-form',
  imports: [ReactiveFormsModule, RouterLink, Loader, Spinner],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  template: `<div class="flex flex-col gap-6">
    <div>
      <h1 class="font-bold text-xl sm:text-3xl dark:text-white text-gray-900">Register intern</h1>
      <p class="mt-1 text-sm dark:text-gray-300 text-gray-700">
        The intern ID is generated by the backend from the join date and ID card type.
      </p>
    </div>

    @if (loadingBatches()) {
      <loader />
    } @else if (!batches().length) {
      <p class="dark:text-gray-300 text-gray-700">
        There are no batches yet — an intern has to belong to one.
        <a routerLink="/batch/new" class="text-primary hover:underline">Create a batch</a> first.
      </p>
    } @else {
      <form [formGroup]="form" (ngSubmit)="submit()" class="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <label class="flex flex-col gap-1">
          <span class="text-sm font-medium dark:text-gray-200 text-gray-700">Name</span>
          <input type="text" formControlName="name" [class]="inputClass" />
          @if (isInvalid('name')) {
            <span class="text-sm text-red-600 dark:text-red-400">Name is required (max 100).</span>
          }
        </label>

        <label class="flex flex-col gap-1">
          <span class="text-sm font-medium dark:text-gray-200 text-gray-700">Email</span>
          <input type="email" formControlName="email" [class]="inputClass" />
          @if (isInvalid('email')) {
            <span class="text-sm text-red-600 dark:text-red-400">A valid email is required.</span>
          }
        </label>

        <label class="flex flex-col gap-1">
          <span class="text-sm font-medium dark:text-gray-200 text-gray-700">Mobile</span>
          <input type="tel" inputmode="tel" formControlName="mobile" [class]="inputClass" />
          @if (isInvalid('mobile')) {
            <span class="text-sm text-red-600 dark:text-red-400">
              10–15 digits, optional leading +.
            </span>
          }
        </label>

        <label class="flex flex-col gap-1">
          <span class="text-sm font-medium dark:text-gray-200 text-gray-700">ID card type</span>
          <select formControlName="idCardType" [class]="inputClass">
            @for (type of idCardTypes; track type) {
              <option [ngValue]="type">{{ type }}</option>
            }
          </select>
        </label>

        <label class="flex flex-col gap-1">
          <span class="text-sm font-medium dark:text-gray-200 text-gray-700">Date of joining</span>
          <input type="date" formControlName="dateOfJoining" [class]="inputClass" />
          @if (isInvalid('dateOfJoining')) {
            <span class="text-sm text-red-600 dark:text-red-400">A joining date is required.</span>
          }
        </label>

        <label class="flex flex-col gap-1">
          <span class="text-sm font-medium dark:text-gray-200 text-gray-700">Batch</span>
          <select formControlName="batchId" [class]="inputClass">
            <option [ngValue]="null" disabled>Select a batch</option>
            @for (batch of batches(); track batch.id) {
              <option [ngValue]="batch.id">
                #{{ batch.id }} · {{ batch.startDate }} → {{ batch.endDate }}
              </option>
            }
          </select>
          @if (isInvalid('batchId')) {
            <span class="text-sm text-red-600 dark:text-red-400">
              Batch is required — an intern can't be saved without one.
            </span>
          }
        </label>

        <div class="flex flex-wrap items-center gap-3 sm:col-span-2">
          <button
            type="submit"
            [disabled]="saving()"
            class="bg-primary flex w-full items-center justify-center gap-2 rounded-lg px-5 py-2 text-white hover:bg-primary-800 dark:hover:bg-primary-400 disabled:cursor-not-allowed disabled:opacity-60 sm:w-auto"
          >
            @if (saving()) {
              <spinner [size]="14" />
            }
            {{ saving() ? 'Registering…' : 'Register intern' }}
          </button>
          <a
            routerLink="/intern"
            class="text-sm dark:text-gray-300 text-gray-700 hover:text-primary dark:hover:text-primary-400"
            >Back to list</a
          >
        </div>
      </form>
    }

    @if (error()) {
      <p
        class="rounded-lg border border-red-300 dark:border-red-800 bg-red-50 dark:bg-red-900/30 px-3 py-2 text-sm text-red-700 dark:text-red-300"
      >
        {{ error() }}
      </p>
    }

    @if (created(); as intern) {
      <div class="rounded-lg border border-gray-200 dark:border-gray-800 px-4 py-3 text-sm">
        <p class="font-medium dark:text-white text-gray-900">
          {{ intern.name }} registered as {{ intern.internId }}
        </p>
        <p class="mt-1 dark:text-gray-300 text-gray-700">
          That ID was generated by the backend — it isn't editable afterwards.
        </p>
        <a routerLink="/intern" class="mt-2 inline-block text-primary hover:underline"
          >Back to interns</a
        >
      </div>
    }
  </div>`
})
export class InternForm implements OnInit {
  private fb = inject(FormBuilder);
  private internService = inject(InternService);
  private batchService = inject(BatchService);
  private toast = inject(ToastService);

  readonly inputClass = INPUT_CLASS;
  readonly idCardTypes: IdCardType[] = ['FREE', 'PREMIUM'];

  // Batch dropdown source — same cached signal the batch pages write to.
  batches = this.batchService.batches;

  loadingBatches = signal<boolean>(true);
  saving = signal<boolean>(false);
  error = signal<string | null>(null);
  created = signal<Intern | null>(null);

  form = this.fb.group({
    name: this.fb.nonNullable.control('', [Validators.required, Validators.maxLength(100)]),
    email: this.fb.nonNullable.control('', [
      Validators.required,
      Validators.email,
      Validators.maxLength(255)
    ]),
    mobile: this.fb.nonNullable.control('', [
      Validators.required,
      Validators.pattern(MOBILE_PATTERN)
    ]),
    idCardType: this.fb.nonNullable.control('FREE' as IdCardType, Validators.required),
    dateOfJoining: this.fb.nonNullable.control('', Validators.required),
    // Starts null on purpose: it's required by the PRD, so pre-selecting the
    // first batch would let an intern land in the wrong one by accident.
    batchId: this.fb.control<number | null>(null, Validators.required)
  });

  ngOnInit(): void {
    this.batchService.list().subscribe({
      next: () => this.loadingBatches.set(false),
      error: err => {
        this.loadingBatches.set(false);
        this.error.set(apiErrorMessage(err));
      }
    });
  }

  isInvalid(name: string): boolean {
    const control = this.form.get(name);
    return !!control && control.invalid && (control.dirty || control.touched);
  }

  submit(): void {
    if (this.form.invalid) {
      // Surfaces the batch/field errors if the user just hit submit blindly.
      this.form.markAllAsTouched();
      return;
    }

    const value = this.form.getRawValue();
    if (value.batchId == null) {
      return;
    }

    this.saving.set(true);
    this.error.set(null);
    this.created.set(null);

    this.internService
      .create({
        name: value.name,
        email: value.email,
        mobile: value.mobile,
        idCardType: value.idCardType,
        dateOfJoining: value.dateOfJoining,
        batchId: value.batchId
      })
      .subscribe({
        next: intern => {
          this.saving.set(false);
          this.created.set(intern);
          this.toast.success(`Intern ${intern.internId} registered.`);
          this.form.reset({ idCardType: 'FREE', batchId: null });
          this.form.markAsPristine();
        },
        error: err => {
          this.saving.set(false);
          this.error.set(apiErrorMessage(err));
          this.toast.error(apiErrorMessage(err));
        }
      });
  }
}
